import mock_image from "../assets/images/Links/eran-link.png";

export const mockItems = [
  {
    id: 1,
    name: "חולצת המיזם",
    description: "חולצת כותנה איכותית עם לוגו המיזם",
    price: 59.9,
    category: "shirts",
    image: mock_image,
    trending: true,
  },
  {
    id: 2,
    name: "צמיד סיליקון",
    description: "צמיד סיליקון עם המסר שלנו",
    price: 15.9,
    category: "accessories",
    image: mock_image,
    trending: true,
  },
  {
    id: 3,
    name: "ספר 'מילים טובות'",
    description: "ספר המלמד על חשיבות השפה החיובית",
    price: 49.9,
    category: "books",
    image: mock_image,
    trending: true,
  },
  {
    id: 4,
    name: "סט מדבקות",
    description: "10 מדבקות מעוצבות עם מסרים חיוביים",
    price: 19.9,
    category: "stickers",
    image: mock_image,
    trending: true,
  },
  {
    id: 5,
    name: "חולצת לוגו זוהר",
    description: "חולצת כותנה עם הדפס זוהר בחושך",
    price: 69.9,
    category: "shirts",
    image: mock_image,
    trending: true,
  },
  {
    id: 6,
    name: "צמיד עור",
    description: "צמיד עור איכותי עם חריטה",
    price: 29.9,
    category: "accessories",
    image: mock_image,
  },
  {
    id: 7,
    name: "ספר 'דרך חדשה'",
    description: "ספר מעורר השראה לחיים טובים יותר",
    price: 54.9,
    category: "books",
    image: mock_image,
  },
  {
    id: 8,
    name: "חולצת V",
    description: "חולצת V מכותנה איכותית",
    price: 49.9,
    category: "shirts",
    image: mock_image,
  },
];
